# Generated by Django 2.2.3 on 2019-07-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko_online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='harga_barang',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
